"""Subprocess entry point: processes a batch of CorelDRAW jobs in one
process, reusing one CorelDRAW instance across them per corel_util's
existing recycle-every-N-jobs pool (SIGNAGE_COREL_RECYCLE_N, defaulted
here to 5 - see module docstring in corel_supervisor.py for why this runs
as a separate OS process at all: a hang inside win32com.client.Dispatch()
itself once took the whole Python process to "Not Responding", something
no in-process timeout can fully guarantee recovery from).

Not meant to be run directly - launched by corel_supervisor.run_batch(),
which passes the jobs file and results file paths.

Writes `results_path` after every job (not just at the end), and a
`<results_path>.heartbeat` file before each step of the *current* job
starts, so the supervisor can report a precise "job N, step X" error if it
has to kill this process for making no progress.

Each job dict (read from `jobs_path`, a JSON list): {"master_path", "shop",
"out_dir", "real_file" (optional), "real_dump_cache" (optional)}. When
"real_file" is given, this also dumps both the freshly-generated "ours"
file and the real designer file via dump_objects.dump() (all COM work for
a validate_all.py-style comparison happens in this one process too, not
just the generate step) - "real_dump_cache", if given and already exists
on disk, is read instead of re-dumping the real file over COM.

A job may instead be {"dump_only": "<path.cdr>", "dump_cache": "<path.json>"
(optional)} - a read-only dump of an already-generated file, with no
CorelEngine.process() call at all. Used by metrics.py-adjacent tools
(cache_ours_dumps.py) to get shape-level data for boards that were already
generated by a previous validate_all.py run, without regenerating them.

Or {"scene_export": "<path.cdr>", "scene_out": "<dir>"} - the editor's scene
export (scene_export.py): opens the file read-only, renders every leaf shape
plus a full-page reference image into `scene_out`, writes scene.json there.
The heartbeat step is "images N/M" while leaf images render.

Or {"export_replay": {"cdr", "scene", "ops", "formats", "options", "out_dir", "base_name",
"assets_dir"?}} - the last is where a swap_image/update_product_slot op's asset resolves against -
Phase D's "Save and Generate" (export_replay.py): replays the editor's operation
list on the converted .cdr, verifies the result and exports the chosen formats.
Heartbeat steps: launch, open, replay i/n, verify, cdr, pdf, png, jpeg.

Or {"render_only": "<path.cdr>", "render_out": "<path.png>"} - a read-only
PNG render of an already-existing file (real designer file or ours), no
CorelEngine.process() call. Used by cache_real_renders.py.
"""
from __future__ import annotations

import json
import os
import sys
import time
from pathlib import Path

os.environ.setdefault("SIGNAGE_COREL_RECYCLE_N", "5")

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from app.engines import CorelEngine  # noqa: E402
from tools.dump_objects import dump as com_dump  # noqa: E402
from app.export_replay import export_from_file  # noqa: E402
from app.scene_export import export_scene_from_file  # noqa: E402
from tools.render_real_preview import render as com_render  # noqa: E402


def _write_json(path: Path, data) -> None:
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
    # On Windows, replacing a file another process happens to be reading at that
    # instant (the supervisor and the web API both poll the heartbeat) raises
    # PermissionError. The clash lasts milliseconds, so retry instead of failing the job.
    for _ in range(60):
        try:
            tmp.replace(path)
            return
        except PermissionError:
            time.sleep(0.05)
    tmp.replace(path)


def main() -> None:
    jobs_path, results_path = Path(sys.argv[1]), Path(sys.argv[2])
    heartbeat_path = results_path.with_suffix(".heartbeat")
    jobs = json.loads(jobs_path.read_text(encoding="utf-8"))

    engine = CorelEngine()
    results: list[dict] = []

    for i, job in enumerate(jobs):
        if job.get("dump_only"):
            def _heartbeat(step_name, _i=i):
                _write_json(heartbeat_path, {"job_index": _i, "shop_name": job["dump_only"], "step": step_name, "at": time.time()})

            _heartbeat("dump_only")
            t0 = time.time()
            entry = {"dump_only": job["dump_only"]}
            try:
                entry["dump"] = com_dump(Path(job["dump_only"]))
                entry["status"] = "done"
                cache_path = Path(job["dump_cache"]) if job.get("dump_cache") else None
                if cache_path:
                    cache_path.parent.mkdir(parents=True, exist_ok=True)
                    _write_json(cache_path, entry["dump"])
            except Exception as e:
                entry["status"] = "error"
                entry["error"] = str(e)
            entry["seconds"] = round(time.time() - t0, 1)
            results.append(entry)
            _write_json(results_path, results)
            continue

        if job.get("scene_export"):
            def _heartbeat(step_name, _i=i):
                _write_json(heartbeat_path, {"job_index": _i, "shop_name": job["scene_export"], "step": step_name, "at": time.time()})

            _heartbeat("scene_export")
            t0 = time.time()
            entry = {"scene_export": job["scene_export"]}
            try:
                scene = export_scene_from_file(Path(job["scene_export"]), Path(job["scene_out"]), on_step=_heartbeat)
                entry["status"] = "done"
                entry["stats"] = scene["stats"]
            except Exception as e:
                entry["status"] = "error"
                entry["error"] = str(e)
            entry["seconds"] = round(time.time() - t0, 1)
            results.append(entry)
            _write_json(results_path, results)
            continue

        if job.get("export_replay"):
            spec = job["export_replay"]

            def _heartbeat(step_name, _i=i):
                _write_json(heartbeat_path, {"job_index": _i, "shop_name": spec["cdr"], "step": step_name, "at": time.time()})

            _heartbeat("launch")
            t0 = time.time()
            entry = {"export_replay": spec["cdr"]}
            try:
                entry["report"] = export_from_file(
                    Path(spec["cdr"]), Path(spec["scene"]), spec["ops"], spec["formats"], spec["options"],
                    Path(spec["out_dir"]), spec["base_name"], on_step=_heartbeat,
                    assets_dir=spec.get("assets_dir"), font_subs=spec.get("font_subs"),
                )
                entry["status"] = "done"
            except Exception as e:
                entry["status"] = "error"
                entry["error"] = f"{type(e).__name__}: {e}"
            entry["seconds"] = round(time.time() - t0, 1)
            results.append(entry)
            _write_json(results_path, results)
            continue

        if job.get("render_only"):
            def _heartbeat(step_name, _i=i):
                _write_json(heartbeat_path, {"job_index": _i, "shop_name": job["render_only"], "step": step_name, "at": time.time()})

            _heartbeat("render_only")
            t0 = time.time()
            entry = {"render_only": job["render_only"]}
            try:
                com_render(Path(job["render_only"]), Path(job["render_out"]))
                entry["status"] = "done"
            except Exception as e:
                entry["status"] = "error"
                entry["error"] = str(e)
            entry["seconds"] = round(time.time() - t0, 1)
            results.append(entry)
            _write_json(results_path, results)
            continue

        shop_name = job["shop"].get("name", "?")

        def _heartbeat(step_name, _i=i, _shop=shop_name):
            _write_json(heartbeat_path, {"job_index": _i, "shop_name": _shop, "step": step_name, "at": time.time()})

        _heartbeat("starting")
        t0 = time.time()
        entry = {"master_path": job["master_path"], "shop": job["shop"], "out_dir": job["out_dir"]}
        try:
            out = engine.process(Path(job["master_path"]), job["shop"], Path(job["out_dir"]), on_step=_heartbeat)
            entry["status"] = "done"
            entry["result"] = out

            if job.get("real_file"):
                _heartbeat("dump_ours")
                ours_cdr = Path(job["out_dir"]) / out["files"]["cdr"]
                entry["ours_dump"] = com_dump(ours_cdr)

                cache_path = Path(job["real_dump_cache"]) if job.get("real_dump_cache") else None
                if cache_path and cache_path.exists():
                    entry["real_dump"] = json.loads(cache_path.read_text(encoding="utf-8"))
                    entry["real_dump_cached"] = True
                else:
                    _heartbeat("dump_real")
                    entry["real_dump"] = com_dump(Path(job["real_file"]))
                    entry["real_dump_cached"] = False
                    if cache_path:
                        cache_path.parent.mkdir(parents=True, exist_ok=True)
                        _write_json(cache_path, entry["real_dump"])
        except Exception as e:
            entry["status"] = "error"
            entry["error"] = str(e)
        entry["seconds"] = round(time.time() - t0, 1)
        results.append(entry)
        _write_json(results_path, results)  # after EVERY job, not just at the end

    try:
        heartbeat_path.unlink()
    except Exception:
        pass
    results_path.with_suffix(".done").write_text("1", encoding="utf-8")


if __name__ == "__main__":
    main()
